=== Justinodactylus/weather-data-parser/src/resources/weather-data.dtd
<!ELEMENT weather_data (EMPTY|station_number)>
<!ELEMENT station_number (#PCDATA|Longitude|Latitude|Version_Number_OF_Stations_Datalogger_Program|UTC_Date)*>
<!ELEMENT Longitude (#PCDATA)>
<!ELEMENT Latitude (#PCDATA)>
<!ELEMENT Version_Number_OF_Stations_Datalogger_Program (#PCDATA)>
<!ELEMENT UTC_Date (#PCDATA|UTC_Time)*>
<!ELEMENT UTC_Time (#PCDATA|Avg_Air_Temperature|Precipitation|Avg_Solar_Radioation|Avg_RH|Soil_Moisture|Soil_Temperature)*>
<!ELEMENT Avg_Air_Temperature (#PCDATA|Avg_Air_Temperature_Last_5_Min|Max_Air_Temperature|Min_Air_Temperature|Infrared_Surface_Temperature_Type)*>
<!ELEMENT Avg_Air_Temperature_Last_5_Min (#PCDATA)>
<!ELEMENT Max_Air_Temperature (#PCDATA)>
<!ELEMENT Min_Air_Temperature (#PCDATA)>
<!ELEMENT Infrared_Surface_Temperature_Type (#PCDATA|Avg_Infrared_Temperature)*>
<!ELEMENT Avg_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Avg|Max_Infrared_Temperature|Min_Infrared_Temperature)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Avg (#PCDATA)>
<!ELEMENT Max_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Max)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Max (#PCDATA)>
<!ELEMENT Min_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Min)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Min (#PCDATA)>
<!ELEMENT Precipitation (#PCDATA)>
<!ELEMENT Avg_Solar_Radioation (#PCDATA|QC_Flag_Solar_Radioation_Avg|Max_Solar_Radioation|Min_Solar_Radioation)*>
<!ELEMENT QC_Flag_Solar_Radioation_Avg (#PCDATA)>
<!ELEMENT Max_Solar_Radioation (#PCDATA|QC_Flag_Solar_Radioation_Max)*>
<!ELEMENT QC_Flag_Solar_Radioation_Max (#PCDATA)>
<!ELEMENT Min_Solar_Radioation (#PCDATA|QC_Flag_Solar_Radioation_Min)*>
<!ELEMENT QC_Flag_Solar_Radioation_Min (#PCDATA)>
<!ELEMENT Avg_RH (#PCDATA|QC_Flag_RH)*>
<!ELEMENT QC_Flag_RH (#PCDATA)>
<!ELEMENT Soil_Moisture (#PCDATA|Avg_Soil_Moisture_5_cm_below| Avg_Soil_Moisture_10_cm_below| Avg_Soil_Moisture_20_cm_below| Avg_Soil_Moisture_50_cm_below| Avg_Soil_Moisture_100_cm_below)*>
<!ELEMENT Avg_Soil_Moisture_5_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_10_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_20_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_50_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_100_cm_below (#PCDATA)>
<!ELEMENT Soil_Temperature (#PCDATA|Avg_Soil_Temperature_5_cm|Avg_Soil_Temperature_10_cm|Avg_Soil_Temperature_20_cm|Avg_Soil_Temperature_50_cm|Avg_Soil_Temperature_100_cm)*>
<!ELEMENT Avg_Soil_Temperature_5_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_10_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_20_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_50_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_100_cm (#PCDATA)>

=== Justinodactylus/weather-data-parser/src/resources/weather-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weather_data SYSTEM "weather-data.dtd"> <!-- Old DOCTYPE definition necessary because parser of python module `lxml` can only validate a xml over a DTD when its defined with DOCTYPE -->
<weather_data>
    <station_number>
        <Longitude></Longitude>
        <Latitude></Latitude>
        <Version_Number_OF_Stations_Datalogger_Program></Version_Number_OF_Stations_Datalogger_Program>
        <UTC_Date>
            <UTC_Time>
                <Avg_Air_Temperature>
                    <Avg_Air_Temperature_Last_5_Min></Avg_Air_Temperature_Last_5_Min>
                    <Max_Air_Temperature></Max_Air_Temperature>
                    <Min_Air_Temperature></Min_Air_Temperature>
                    <Infrared_Surface_Temperature_Type>
                        <Avg_Infrared_Temperature>
                            <QC_Flag_Infrared_Surface_Temperature_Avg></QC_Flag_Infrared_Surface_Temperature_Avg>
                            <Max_Infrared_Temperature>
                                <QC_Flag_Infrared_Surface_Temperature_Max></QC_Flag_Infrared_Surface_Temperature_Max>
                            </Max_Infrared_Temperature>
                            <Min_Infrared_Temperature>
                                <QC_Flag_Infrared_Surface_Temperature_Min></QC_Flag_Infrared_Surface_Temperature_Min>
                            </Min_Infrared_Temperature>
                        </Avg_Infrared_Temperature>
                    </Infrared_Surface_Temperature_Type>
                </Avg_Air_Temperature>
                <Precipitation></Precipitation>
                <Avg_Solar_Radioation>
                    <QC_Flag_Solar_Radioation_Avg></QC_Flag_Solar_Radioation_Avg>
                    <Max_Solar_Radioation>
                        <QC_Flag_Solar_Radioation_Max></QC_Flag_Solar_Radioation_Max>
                    </Max_Solar_Radioation>
                    <Min_Solar_Radioation>
                        <QC_Flag_Solar_Radioation_Min></QC_Flag_Solar_Radioation_Min>
                    </Min_Solar_Radioation>
                </Avg_Solar_Radioation>
                <Avg_RH>
                    <QC_Flag_RH></QC_Flag_RH>
                </Avg_RH>
                <Soil>
                    <Soil_Moisture>
                        <Avg_Soil_Moisture_5_cm_below></Avg_Soil_Moisture_5_cm_below>
                        <Avg_Soil_Moisture_10_cm_below></Avg_Soil_Moisture_10_cm_below>
                        <Avg_Soil_Moisture_20_cm_below></Avg_Soil_Moisture_20_cm_below>
                        <Avg_Soil_Moisture_50_cm_below></Avg_Soil_Moisture_50_cm_below>
                        <Avg_Soil_Moisture_100_cm_below></Avg_Soil_Moisture_100_cm_below>
                    </Soil_Moisture>
                    <Soil_Temperature>
                        <Avg_Soil_Temperature_5_cm></Avg_Soil_Temperature_5_cm>
                        <Avg_Soil_Temperature_10_cm></Avg_Soil_Temperature_10_cm>
                        <Avg_Soil_Temperature_20_cm></Avg_Soil_Temperature_20_cm>
                        <Avg_Soil_Temperature_50_cm></Avg_Soil_Temperature_50_cm>
                        <Avg_Soil_Temperature_100_cm></Avg_Soil_Temperature_100_cm>
                    </Soil_Temperature>
                </Soil>
            </UTC_Time>
        </UTC_Date>
    </station_number>
</weather_data>
