=== Justinodactylus/weather-data-parser/src/resources/weather-data-monthly.dtd
<!ELEMENT weather_data (EMPTY|station_number)>
<!ELEMENT station_number (#PCDATA|Longitude|Latitude|Version_Number_OF_Stations_Datalogger_Program|UTC_Date)*>
<!ELEMENT Longitude (#PCDATA)>
<!ELEMENT Latitude (#PCDATA)>
<!ELEMENT Version_Number_OF_Stations_Datalogger_Program (#PCDATA)>
<!ELEMENT UTC_Date (#PCDATA|Temperature|Precipitation|Avg_Daily_Total_Solar_Energy|Infrared_Surface_Temperature_Type)*>
<!ELEMENT Temperature (#PCDATA|Max_Air_Temperature|Min_Air_Temperature|Mean_Air_Temperature|Avg_Air_Temperature)*>
<!ELEMENT Max_Air_Temperature (#PCDATA)>
<!ELEMENT Min_Air_Temperature (#PCDATA)>
<!ELEMENT Mean_Air_Temperature (#PCDATA)>
<!ELEMENT Avg_Air_Temperature (#PCDATA)>
<!ELEMENT Precipitation (#PCDATA)>
<!ELEMENT Avg_Daily_Total_Solar_Energy (#PCDATA)>
<!ELEMENT Infrared_Surface_Temperature_Type (#PCDATA|Max_Infrared_Temperature|Min_Infrared_Temperature|Avg_Infrared_Temperature)*>
<!ELEMENT Max_Infrared_Temperature (#PCDATA)>
<!ELEMENT Min_Infrared_Temperature (#PCDATA)>
<!ELEMENT Avg_Infrared_Temperature (#PCDATA)>

=== Justinodactylus/weather-data-parser/src/resources/weather-data-monthly.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weather_data SYSTEM "weather-data-monthly.dtd"> <!-- Old DOCTYPE definition necessary because parser of python module `lxml` can only validate a xml over a DTD when its defined with DOCTYPE -->
<weather_data>
    <station_number>
        <Longitude></Longitude>
        <Latitude></Latitude>
        <Version_Number_OF_Stations_Datalogger_Program></Version_Number_OF_Stations_Datalogger_Program>
        <UTC_Date>
            <Temperature>
                <Max_Air_Temperature></Max_Air_Temperature>
                <Min_Air_Temperature></Min_Air_Temperature>
                <Mean_Air_Temperature></Mean_Air_Temperature>
                <Avg_Air_Temperature></Avg_Air_Temperature>
            </Temperature>
            <Precipitation></Precipitation>
            <Avg_Daily_Total_Solar_Energy></Avg_Daily_Total_Solar_Energy>
            <Infrared_Surface_Temperature_Type>
                <Max_Infrared_Temperature></Max_Infrared_Temperature>
                <Min_Infrared_Temperature></Min_Infrared_Temperature>
                <Avg_Infrared_Temperature></Avg_Infrared_Temperature>
            </Infrared_Surface_Temperature_Type>
        </UTC_Date>
    </station_number>
</weather_data>
