=== Justinodactylus/weather-data-parser/src/resources/weather-data-daily.dtd
<!ELEMENT weather_data (EMPTY|station_number)>
<!ELEMENT station_number (#PCDATA|Longitude|Latitude|Version_Number_OF_Stations_Datalogger_Program|UTC_Date)*>
<!ELEMENT Longitude (#PCDATA)>
<!ELEMENT Latitude (#PCDATA)>
<!ELEMENT Version_Number_OF_Stations_Datalogger_Program (#PCDATA)>
<!ELEMENT UTC_Date (#PCDATA|Temperature|Precipitation|Total_Solar_Energy|Infrared_Surface_Temperature_Type|RH|Soil_Moisture|Soil_Temperature)*>
<!ELEMENT Temperature (#PCDATA|Max_Air_Temperature|Min_Air_Temperature|Mean_Air_Temperature|Avg_Air_Temperature)*>
<!ELEMENT Max_Air_Temperature (#PCDATA)>
<!ELEMENT Min_Air_Temperature (#PCDATA)>
<!ELEMENT Mean_Air_Temperature (#PCDATA)>
<!ELEMENT Avg_Air_Temperature (#PCDATA)>
<!ELEMENT Precipitation (#PCDATA)>
<!ELEMENT Total_Solar_Energy (#PCDATA)>
<!ELEMENT Infrared_Surface_Temperature_Type (#PCDATA|Max_Infrared_Temperature|Min_Infrared_Temperature|Avg_Infrared_Temperature)*>
<!ELEMENT Max_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Max)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Max (#PCDATA)>
<!ELEMENT Min_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Min)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Min (#PCDATA)>
<!ELEMENT Avg_Infrared_Temperature (#PCDATA|QC_Flag_Infrared_Surface_Temperature_Avg)*>
<!ELEMENT QC_Flag_Infrared_Surface_Temperature_Avg (#PCDATA)>
<!ELEMENT RH (#PCDATA|Max_RH|Min_RH|Avg_RH)*>
<!ELEMENT Max_RH (#PCDATA)>
<!ELEMENT Min_RH (#PCDATA)>
<!ELEMENT Avg_RH (#PCDATA)>
<!ELEMENT Soil_Moisture (#PCDATA|Avg_Soil_Moisture_5_cm_below| Avg_Soil_Moisture_10_cm_below| Avg_Soil_Moisture_20_cm_below| Avg_Soil_Moisture_50_cm_below| Avg_Soil_Moisture_100_cm_below)*>
<!ELEMENT Avg_Soil_Moisture_5_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_10_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_20_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_50_cm_below (#PCDATA)>
<!ELEMENT Avg_Soil_Moisture_100_cm_below (#PCDATA)>
<!ELEMENT Soil_Temperature (#PCDATA|Avg_Soil_Temperature_5_cm|Avg_Soil_Temperature_10_cm|Avg_Soil_Temperature_20_cm|Avg_Soil_Temperature_50_cm|Avg_Soil_Temperature_100_cm)*>
<!ELEMENT Avg_Soil_Temperature_5_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_10_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_20_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_50_cm (#PCDATA)>
<!ELEMENT Avg_Soil_Temperature_100_cm (#PCDATA)>

=== Justinodactylus/weather-data-parser/src/resources/weather-data-daily.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE weather_data SYSTEM "weather-data-daily.dtd"> <!-- Old DOCTYPE definition necessary because parser of python module `lxml` can only validate a xml over a DTD when its defined with DOCTYPE -->
<weather_data>
    <station_number>
        <Longitude></Longitude>
        <Latitude></Latitude>
        <Version_Number_OF_Stations_Datalogger_Program></Version_Number_OF_Stations_Datalogger_Program>
        <UTC_Date>
            <Temperature>
                <Max_Air_Temperature></Max_Air_Temperature>
                <Min_Air_Temperature></Min_Air_Temperature>
                <Mean_Air_Temperature></Mean_Air_Temperature>
                <Avg_Air_Temperature></Avg_Air_Temperature>
            </Temperature>
            <Precipitation></Precipitation>
            <Total_Solar_Energy></Total_Solar_Energy>
            <Infrared_Surface_Temperature_Type>
                <Max_Infrared_Temperature></Max_Infrared_Temperature>
                <Min_Infrared_Temperature></Min_Infrared_Temperature>
                <Avg_Infrared_Temperature></Avg_Infrared_Temperature>
            </Infrared_Surface_Temperature_Type>
            <RH>
                <Avg_RH></Avg_RH>
                <Max_RH></Max_RH>
                <Min_RH></Min_RH>
            </RH>
            <Soil_Moisture>
                <Avg_Soil_Moisture_5_cm_below></Avg_Soil_Moisture_5_cm_below>
                <Avg_Soil_Moisture_10_cm_below></Avg_Soil_Moisture_10_cm_below>
                <Avg_Soil_Moisture_20_cm_below></Avg_Soil_Moisture_20_cm_below>
                <Avg_Soil_Moisture_50_cm_below></Avg_Soil_Moisture_50_cm_below>
                <Avg_Soil_Moisture_100_cm_below></Avg_Soil_Moisture_100_cm_below>
            </Soil_Moisture>
            <Soil_Temperature>
                <Avg_Soil_Temperature_5_cm></Avg_Soil_Temperature_5_cm>
                <Avg_Soil_Temperature_10_cm></Avg_Soil_Temperature_10_cm>
                <Avg_Soil_Temperature_20_cm></Avg_Soil_Temperature_20_cm>
                <Avg_Soil_Temperature_50_cm></Avg_Soil_Temperature_50_cm>
                <Avg_Soil_Temperature_100_cm></Avg_Soil_Temperature_100_cm>
            </Soil_Temperature>
        </UTC_Date>
    </station_number>
</weather_data>
